#!/usr/bin/env bash
# program that shows "To infinity and beyond" 
# indefinitely with a sleep 2 in between each iteration.
# Displays "I am invincible!!!" in between each iteration.
# if terminating signal is received

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
