#!/usr/bin/env bash
# A Bash script that displays the content of the file /etc/passwd.
# It displays username, user id, Home directory path for the user

while read -r cont
do
	echo "$cont" | cut -d ':' -f 1,3,6
done < "/etc/passwd"
