#!/usr/bin/env bash
# display the contents of the `/etc/passwd` file.

while IFS=':' read -r user_name password uid gid info home user_shell;
do
  echo "The user $user_name is part of the $gid gang,"\
  "lives in $home and rides $user_shell."\
  "$uid's place is protected by the passcode $password,"\
  "more info about the user here: $info"
done < "/etc/passwd"
