#!/usr/bin/env bash
#This script displays contents of the current directory
# but displays just the name after the first dash (-)

content=$(ls)

for cont in $contents
do
	echo "$cont" | cut -d '-' -f2
done
